### ISSUE TITLE
Abstract Stories

### ISSUE THREAD

**Issue by thedrow** [dry-python/stories#328]
Currently there's no way to create an abstract class with an abstract method that *must be* a story in subclasses inheriting from the abstract base class.

This is useful when you want the implementer to rely on the fact that `obj.story.run()` is always available.

Suppose you have a story composed of multiple unknown substories and you'd like the user of your library to implement.

```python
class Service:
  @story
  def start(I):
    I.initialize
    I.start
    I.on_started
```

Naturally in this case, you can use composition to provide the substories.
However, sometimes it is simply not necessary. Instead we can mandate the user to implement those substories in the subclass:

```python
from abc import ABC

class Service(ABC):
  @story
  def start(I):
    I.initialize
    I.start
    I.on_started

   @abstractstory
   def initialize(I):
     pass

   @abstractstory
   def start(I):
     pass

   @abstractstory
   def on_started(I):
     pass
```

Composition is useful when the implementation is not specific. In this case, it is very specific.

**Comment by proofit404** [comment]
Do you mean using [abc.Meta](https://docs.python.org/3/library/abc.html) in the class that also contains the story definition? Like
```python
from abc import ABC

class AbstractAction(ABC):
    @story
    def do(I):
        I.one
        I.two
        I.three

    @abstractmethod
    def one(self, ctx):
        ...

    @abstractmethod
    def two(self, ctx):
        ...

    @abstractmethod
    def three(self, ctx):
        ...
```
I assume it should work already.

**Comment by thedrow** [comment]
No I mean the other way around.

```python
from abc import ABC

class AbstractAction(ABC):
    @abstractstory
    def do(I):
        pass

class Action(AbstractAction):
    @story
    def do(I):
        I.one

    def one(self, ctx):
        pass
```

I'll edit the description to explain why.

**Comment by proofit404** [comment]
It could have a valid use case for such a feature.

If it supposed to help only with type checking and nothing else it could be a good candidate for [editors project](https://github.com/dry-python/editors/issues?q=is%3Aopen+is%3Aissue+label%3Astories+label%3Atypechecker).

Also, is it possible that `dependencies` library solves the problem in a better way?

**Comment by thedrow** [comment]
It's supposed to force the implementer to use a specific design as any usage of abstract classes.

**Dependency Inversion** is suitable whenever you have an interchangeable implementation of a functionality. Usually that implementation is a cross-cutting concern such as logging.
The relationship itself between the main component and the inverted dependency will be described using the phrase `has a`. For example: A door **`has a`** lock.
The lock object is interchangeable since there are many types of locks.

In this case, using an Inversion of Control Container library such as `dependencies` is the solution.

If we continue using that metaphor, some doors can have multiple locks. Others don't have locks at all.
If we create a story about opening a door we need the implementer to specify exactly how it is going to open. That's because a door with multiple locks **`is a`** door.
In this case the implementation is specific to that door and creating a generic object to describe it may not be enough.

For example: I have a secure door to a safe that requires you to open the locks successfully in order.
Failing to do so with permanently lock the door.

This is a very specific implementation and it is exactly why **Open/Close** exists.

**Comment by proofit404** [comment]
> That's because a door with multiple locks is a door which implies you should be using inheritance.

I'm not sure it does this.

We could use dependency injection to inject stories inside the stories. That way you could have multiple stories explaining the steps you need to take to open the door. And the client code (a parent story) will happily work with any story.

This also would give us more flexibility. Client code (a parent story) does not dictate what name should implementer code (a child story) has. In the documentation, we have the statement that users are free to put their stories in whatever classes they like. Even if it is a Django model. Also, #113 will make this approach even more powerful.
 
I have a question related to the proposed `abstractstory` behavior. Will it require all implementations to have the same set of the `@arguments`? I think it should because otherwise, it will break the Liskov substitution principle.

To be honest I want any library of the dry-python project to force exactly one way to solve one problem. `stories`, `dependencies` and `mappers` designed to work together in the best possible way. This feature will contradict this approach a little bit.

**Comment by thedrow** [comment]
> I have a question related to the proposed `abstractstory` behavior. Will it require all implementations to have the same set of the `@arguments`? I think it should because otherwise, it will break the Liskov substitution principle.

Correct.

**Comment by proofit404** [comment]
I can't decide if I like this idea or not.

From one point of view, the dry-python project is completely against inheritance in favor of composition. This is the reason we've built the `dependencies` library in the first place. And we design everything in stories and mappers to be compatible with it.

From the other side, it may be a valid feature for some users who use the `stories` library as a standalone solution and they do `abc` a lot.

Could this be implemented as a separate library?

**Comment by thedrow** [comment]
> Could this be implemented as a separate library?

I'm not sure yet. Maybe.

**Comment by proofit404** [comment]
I think we could keep it this way for now, and if it accepts a lot of attention from the community we'll move it into `stories.contrib.abc`. It is even possible to extend the `editors` upgrade utility to handle this transition automatically in the future.

I'm happy to refer to this library in the `stories` documentation somewhere.

If we need to expose some details about the story definition, we could discuss it in a separate issue.

Feel free to ask for help, if you stuck in the development of it as a separate package.

Marking it as won't fix for now, since it's not gonna land in the main repo yet.

Have a good day :tada:
